def generate_ai_summary(
    amount,
    category,
    description
):

    return f"""
=================================

AI EXPENSE ANALYSIS REPORT

=================================

Expense Amount:
₹{amount}

Expense Category:
{category}

Description:
{description}

Expense Assessment:
The reimbursement request appears valid based on the submitted information.

AI Recommendation:
Recommended for administrative review and verification.

Risk Analysis:
Low Risk

Approval Suggestion:
Likely to be approved after bill verification.

Generated By:
AI Reimbursement Management System

=================================
"""