def generate_summary(
    amount,
    category,
    description
):

    return f"""
=================================

AI EXPENSE ANALYSIS REPORT

=================================

Expense Amount:
₹{amount}

Expense Category:
{category}

Description:
{description}

Expense Assessment:
The submitted reimbursement request has been analyzed based on the provided expense details and category information.

AI Recommendation:
The expense appears reasonable and suitable for reimbursement processing. Supporting documents should be verified by the administrator before approval.

Risk Analysis:
Low Risk

Suggested Action:
Proceed with administrative review and approval workflow.

Generated By:
AI Reimbursement Management System

=================================
"""